export default {
	"govt": [
		{
			"name" : "Confederation",
			"class"   : [ 0 ],
			"allies"  : [],
			"enemies" : [ 1 ],
			"xenophobic"    : false,
			"neverAttacks"  : false,
			"alwaysAttacks" : false,
			"startDisabled" : false,
			"immune"        : false,
			"unhelped"      : false,
			"pretendPods"   : true,
			"targetName" : "Confed",
			"hailName"   : "Confed",
			"mediumName" : "Confederation",
			"mapColor"   : "#000000",
			"ignoreHails"   : false,
			"freeAssist"    : false,
			"disableAssist" : false,
			"noDistress"    : false,
			"voiceType"  : 0,
			"skillMult"  : 100,
			"maxOdds"    : -1,
			"interface"  : 0,
			"newsPic"    : 0,
			"shipPaint"  : "",
			"preferHypergate" : false,
			"preferWormhole"  : false,
			"neverUseHypergate" : false,
			"retreatLowShield" : true,
			"crimeTolerance" : 50,
			"initalRecord"   : 0,
			"smugglePenalty" : 3,
			"destroyPenalty" : 25,
			"disablePenalty" : 5,
			"boardPenalty"   : 10,
			"attackForeignCriminal" : true,
			"plunder"               : false,
			"smuggleFineType" : 0,
			"smuggleFine"     : -1,
			"cargoScanMask"   : "0",
			"requireToLand"   : "",
			"bribeWarships"   : true,
			"bribeFreighters" : true,
			"bribeSpobs"      : true,
			"greedy"          : false,
			"jamming"           : [0, 0, 0, 0],
			"freightersWeakJam" : false
		}
	]
}
